version: "3"
services:
  database:
    image: postgres:12.7-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD required.}

  backend:
    build: ./backend
    command: gunicorn -b 0.0.0.0:8000 --worker-class=gevent --timeout=3600 --worker-connections=1000 --workers=5 backend.wsgi
    volumes:
      - ./backend:/app
      - static_files:/app/static
    ports:
      - "${DEBUGGER_PORT:?required}:${DEBUGGER_PORT:?required}"
      - 8000:8000
    depends_on:
      - database
    environment:
      SECRET_KEY: ${SECRET_KEY:?SECRET_KEY required}
      FERNET_KEY: ${FERNET_KEY:?FERNET_KEY required}
      TZ: America/Argentina/Buenos_Aires
      #db connection
      DB_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD required.}
      #debug
      DEBUGGER_PORT: ${DEBUGGER_PORT:?required}
      DEBUGGER_ENABLE: ${DEBUGGER_ENABLE}
      #url
      DOMAIN: ${DOMAIN}
      PROTOCOL: ${PROTOCOL}
      GEVENT_SUPPORT: "True"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    ports:
      - 8001:8001

  nginx_server:
    build: ./nginx_server
    volumes:
      - static_files:/home/app/static
    ports:
      - 443:443
    depends_on:
      - backend
      - frontend

volumes:
  db_data:
  static_files:
