# Generated by Django 4.1.7 on 2023-02-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resenias', '0001_creacion_modelos'),
    ]

    operations = [
        migrations.AddField(
            model_name='resenia',
            name='autor',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
    ]
