# Generated by Django 4.1.7 on 2023-03-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resenias', '0002_resenia_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenia',
            name='contenido',
            field=models.TextField(help_text='Escriba su reseña en este campo.', max_length=2500),
        ),
    ]
